source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use postgresql as the database for Active Record
gem 'pg'
# CSS Compressor
gem 'yui-compressor', '0.12.0'
# JavaScript Compressor
gem 'uglifier', '2.4.0'
# Less Asset Pipeline
gem 'therubyracer', '0.12.0', platform: :ruby
# Twitter Bootstrap
gem 'less-rails-bootstrap', '3.0.6'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

gem 'rb-appscript'

gem 'resque', '~> 1.x'

gem 'dotenv'

group :development do
  gem 'foreman'
  gem 'lunchy'
end

group :test do
  gem 'rspec-rails'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
end
